### ISSUE TITLE
Support netstandard2.0

### ISSUE THREAD

**Issue by fubar-coder** [beginor/nhibernate-extensions#12]
Hi,

it would be nice if the package would (also) target netstandard2.0. This would allow frameworks other than .NET 8.

Thank you for your effort 😄

**Comment by fubar-coder** [comment]
I'd argue that netstandard2.0 support would be beneficial, because it'd enable more people to use this library and you don't need features that aren't supported on .NET Standard 2.0. In other words: IMO there is no reason to use a target framework which is more restricting than the target framework used by NHibernate.

**Comment by beginor** [comment]
OK, if you really need `netstandard2.0` , do you like to make a pr and add `netstandard2.0` support?

Pr is always welcome!
