### ISSUE TITLE
Using in a singleton service

### ISSUE THREAD

**Issue by Harpush** [beginor/nhibernate-extensions#7]
Is there any way to avoid the scoped lifetime from requiring all the stack above to be scoped? Something like how HttpContextAccessor works?

**Comment by Harpush** [comment]
> You can write your own extension methods, register your required service as singleton.
> 
> And `Configuration` and `ISessionFactory` are registered as singleton, you can use `ISessionFactory` in a singleton services.
> 
> But register `ISession` as singleton is not recomended.

I meant keep session as scoped but allow access to it in singleton services. Maybe throughtbhttp context? Asynclocal?

**Comment by beginor** [comment]
What about using `ISessionFactory` a singleton service, you can open a session any where you like just call `sessionFactory.OpenSession()`?

**Comment by Harpush** [comment]
> What about using `ISessionFactory` a singleton service, you can open a session any where you like just call `sessionFactory.OpenSession()`?

Maybe I am wrong here but the recommended approach is once per request. But making ISession scoped means it affect everything above to be scoped. What I would like is inject X that allows access to a scoped session in singleton methods. Same as HttpContextAccessor

**Comment by beginor** [comment]
As I know, we can only inject parameters to class constructor, and can not inject parameters to class methods. 

If you want access scoped service in a singleton class (maybe like in middleware),  you can inject global `IServiceProvider` instance to your singleton class, and call `service.CreateScope()` to access scoped services. 

If your singleton service is http related, you can get scoped service from current httpcontext's service provider like `context.RequestServices.GetService()`.

Hope this can help you.
